# fly.toml app configuration file generated for frontend-summer-voice-777 on 2024-11-08T18:43:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-summer-voice-777'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
